# kick: 0

version: 2.1

commands:
  run_tests:
    description: "Build libyuv-node and run the test suite"
    parameters:
      version:
        type: string
    steps:
      - run: apt install cmake
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
          - v1-dependencies-<< parameters.version >>-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
      - run: npm test
jobs:
  node-14:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "14"
  node-12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "12"
  node-10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "10"
  node-8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "8"

workflows:
  version: 2
  build:
    jobs:
      - node-12
      - node-11
      - node-10
      - node-8
